version: "3.5"

services:
  app:
    build: .
    volumes:
      - ./src:/go/src/app
    environment:
      - DOCKER_ADDRESS=docker
      - DOCKER_PORT=2375
      - REGISTRY_ADDRESS=registry
      - REGISTRY_PORT=5000
      - RABBITMQ_HOST=rabbitmq
      - CONSUMER_QUEUE=apps.deploy.req
      - PRODUCER_QUEUE=apps.deploy.res

  docker:
    image: docker:20.10.6-dind
    command:
      - --insecure-registry=registry:5000
    environment:
      - DOCKER_TLS_CERTDIR=
    privileged: true

  registry:
    image: registry:2.7.1

networks:
  default:
    name: climb
